<?php

function ae_schema() {
    $schema['ae_config'] = array(
   'fields' => array(
     'id'=>array(
       'type'=>'serial',
       'not null' => TRUE,
     ),
     'api_key'=>array(
       'type' => 'varchar',
       'length' => 60,
       'not null' => TRUE,
     ),
     'social_logins'=>array(
       'type' => 'varchar',
       'length' => 100,
       'not null' => TRUE,
     ),
   ),
   'primary key' => array('id'),
 );

 return $schema;
}


?>