<?php

function ae_theme($existing, $type, $theme, $path) {
  return [
    'signup' => [
      'variables' => [
          'socials' => [],
          'fields' => [],
          'flow_css' => [],
          'want_email' => NULL,
          'auth_window' => NULL,
          'close_button' => NULL,
          'sso' => NULL,
          'date_format' => NULL,
          'new_user' => NULL,
          'extra_info' => [],
      ],
    ],
  ];
}