<?php

function ae_theme($existing, $type, $theme, $path) {
  return [
      'aemenu' => [
          'variables' => [
              'socials' => [],
              'framework_url' => NULL,
              'fields' => [],
              'general_settings' => [],
              'basic_options' => [],
              'email_options' => [],
              'text_options' => [],
              'performance_options' => []
          ],
      ],
      'signup' => [
          'variables' => [
              'socials' => [],
              'fields' => [],
          ],
      ]
  ];
}

