<?php

function ae_theme($existing, $type, $theme, $path) {
  return [
      'aemenu' => [
          'variables' => [
              'socials' => [],
              'framework_url' => NULL,
              'fields' => [],
              'general_settings' => [],
              'basic_options' => [],
              'email_options' => [],
              'text_options' => [],
              'performance_options' => []
          ],
      ],
      'signup' => [
          'variables' => [
              'socials' => [],
              'fields' => [],
          ],
      ],
      'setting' => [
          'variables' => [
              'heading' => NULL
          ],
      ]
  ];
}

function ae_page_attachments_alter(&$page) {
$page['#attached']['library'][] = 'ae/script';
    $page['#attached']['drupalSettings']['ae']['data']['foo'] = 'bar';
}

function ae_page_attachments(array &$attachments) {
    drupal_set_message("Adding Javascript");
    // Unconditionally attach an asset to the page.
    $attachments['#attached']['library'][] = 'ae/script';
}